import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import MobileNavbar from "./MobileNavbar"; // client component


const inter = Inter({ subsets: ["latin"], });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* Navbar */}
        <MobileNavbar/>

        {/* Page content */}
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
