import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Top black navbar */}
        <nav className="w-full bg-black text-white flex justify-center gap-2">
          <Link href="/" className="navButton">Home</Link>
          <Link href="/Service1" className="navButton">Service 1</Link>
          <Link href="/Service2" className="navButton">Service 2</Link>
          <Link href="/Service3" className="navButton">Service 3</Link>
        </nav>

        {/* Push content below navbar */}
        <main className="mt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
